name: Hello World!

on: push

jobs:
    hello_world_job:
        name: Hello World Job
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: | 
                echo Hello World!
    now_it_is:
        name: Date Job
        runs-on: ubuntu-latest
        steps:
            - name: Now it is
              run: date
    directory_content:
        name: Dir Content job
        runs-on: ubuntu-latest
        steps:
            - name: Directory content
              run: ls -l
